spring.application.name=interior-design-backend

server.port=8080

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/interior_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MYSQLPASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (good for debugging)
spring.jpa.properties.hibernate.format_sql=true